### ISSUE TITLE
How to get the Names and Phone number of contacts 

### ISSUE THREAD

**Issue by NileshArnaiya** [Zer0bee/ContactListener#1]
How to get the Names and Phone numbers of contacts that were added/deleted/modified?
I get the Hash Key in the integer value but how to use it? Thanks in advance.

**Comment by Zer0bee** [comment]
Whenever you call this `HashMap<Integer, HashSet<Integer>> update = ContactHelper.getInstance(this).update();`, you get list of contact_id in HashSet<Integer>, which can be used to fetch all the contact info like name and phone number from android contact db.

**Comment by NileshArnaiya** [comment]
Hi, Thanks for the answer @Zer0bee , I'm still a little confused on how to get the contacts using Integer contact_id coz mostly contact_id's are strings 
This is what I've tried - 
```
 for (Integer integer : next.getValue()) {
                Log.d("MainActivity2", "onContactCheck: " + action_name + ":" + integer);
                ArrayList<String> phones = new ArrayList<String>();

                Cursor cursor2 = getContentResolver().query(
                        ContactsContract.Contacts.CONTENT_URI,
                        null,
                        ContactsContract.Contacts._ID +" = ?",
                        new String[]{"" + integer + ""}, null);

                while (cursor2.moveToNext())
                {
                    phones.add(cursor2.getString(cursor2.getColumnIndex(ContactsContract.Contacts.DISPLAY_NAME)));
                }
```
The database only has two integers id and hash - how do I query the contacts 
what is the right way?  Could you please provide an example? that would be very helpful

**Comment by NileshArnaiya** [comment]
Hi, Anything on this? Will really appreciate it.
